// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Milestone_1.Data;

namespace Milestone_1.Migrations
{
    [DbContext(typeof(TwitterContext))]
    [Migration("20191101225514_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Milestone_1.models.Followers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserToFollowId");

                    b.Property<int>("userMeId");

                    b.HasKey("id");

                    b.ToTable("followers");
                });

            modelBuilder.Entity("Milestone_1.models.Tweets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("post_date");

                    b.Property<string>("tweet");

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("tweets");
                });

            modelBuilder.Entity("Milestone_1.models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("login");

                    b.Property<string>("password");

                    b.Property<int>("userdata");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Milestone_1.models.UserData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("city");

                    b.Property<string>("country");

                    b.Property<string>("gender");

                    b.Property<string>("name");

                    b.Property<string>("surname");

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("userDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
