// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Milestone_1.Data;

namespace Milestone_1.Migrations
{
    [DbContext(typeof(TwitterContext))]
    [Migration("20191101223828_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Milestone_1.models.User", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("login");

                    b.Property<string>("password");

                    b.Property<int?>("userdataid");

                    b.HasKey("id");

                    b.HasIndex("userdataid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Milestone_1.models.UserData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("city");

                    b.Property<string>("country");

                    b.Property<string>("gender");

                    b.Property<string>("name");

                    b.Property<string>("surname");

                    b.Property<int>("userId");

                    b.HasKey("id");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("Milestone_1.models.User", b =>
                {
                    b.HasOne("Milestone_1.models.UserData", "userdata")
                        .WithMany()
                        .HasForeignKey("userdataid");
                });
#pragma warning restore 612, 618
        }
    }
}
