// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Milestone_1.Data;

namespace Milestone_1.Migrations
{
    [DbContext(typeof(TwitterContext))]
    [Migration("20191102010518_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Milestone_1.models.Comment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Tweetsid");

                    b.Property<int?>("UserDataId");

                    b.Property<string>("commentText");

                    b.HasKey("id");

                    b.HasIndex("Tweetsid");

                    b.HasIndex("UserDataId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Milestone_1.models.Followers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("UserDataId");

                    b.Property<int>("UserToFollowForeignKey");

                    b.Property<int?>("UserToFollowid");

                    b.HasKey("id");

                    b.HasIndex("UserDataId");

                    b.HasIndex("UserToFollowid");

                    b.ToTable("followers");
                });

            modelBuilder.Entity("Milestone_1.models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("discription");

                    b.Property<string>("name");

                    b.HasKey("GroupId");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Milestone_1.models.Tweets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GroupId");

                    b.Property<int?>("UserDataId");

                    b.Property<DateTime>("post_date");

                    b.Property<string>("tweetText");

                    b.HasKey("id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserDataId");

                    b.ToTable("tweets");
                });

            modelBuilder.Entity("Milestone_1.models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("login");

                    b.Property<string>("password");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Milestone_1.models.UserData", b =>
                {
                    b.Property<int>("UserDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("UserForeignKey");

                    b.Property<string>("city");

                    b.Property<string>("country");

                    b.Property<string>("gender");

                    b.Property<string>("name");

                    b.Property<string>("surname");

                    b.HasKey("UserDataId");

                    b.HasIndex("UserForeignKey")
                        .IsUnique();

                    b.ToTable("userDatas");
                });

            modelBuilder.Entity("Milestone_1.models.UserDataGroup", b =>
                {
                    b.Property<int>("UserDataId");

                    b.Property<int>("GroupId");

                    b.HasKey("UserDataId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserDataGroup");
                });

            modelBuilder.Entity("Milestone_1.models.Comment", b =>
                {
                    b.HasOne("Milestone_1.models.Tweets", "Tweets")
                        .WithMany("Comments")
                        .HasForeignKey("Tweetsid");

                    b.HasOne("Milestone_1.models.UserData", "UserData")
                        .WithMany()
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("Milestone_1.models.Followers", b =>
                {
                    b.HasOne("Milestone_1.models.UserData", "UserData")
                        .WithMany("Followers")
                        .HasForeignKey("UserDataId");

                    b.HasOne("Milestone_1.models.User", "UserToFollow")
                        .WithMany()
                        .HasForeignKey("UserToFollowid");
                });

            modelBuilder.Entity("Milestone_1.models.Tweets", b =>
                {
                    b.HasOne("Milestone_1.models.Group", "Group")
                        .WithMany("Tweets")
                        .HasForeignKey("GroupId");

                    b.HasOne("Milestone_1.models.UserData", "UserData")
                        .WithMany("Tweets")
                        .HasForeignKey("UserDataId");
                });

            modelBuilder.Entity("Milestone_1.models.UserData", b =>
                {
                    b.HasOne("Milestone_1.models.User", "User")
                        .WithOne("UserData")
                        .HasForeignKey("Milestone_1.models.UserData", "UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Milestone_1.models.UserDataGroup", b =>
                {
                    b.HasOne("Milestone_1.models.Group", "Group")
                        .WithMany("UserDataGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Milestone_1.models.UserData", "UserData")
                        .WithMany("UserDataGroups")
                        .HasForeignKey("UserDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
